### Show documentation - README.md
GET http://localhost:5000/ HTTP/1.1

### Show billboard information - available/occuppied space
@is_occupied=1
GET http://localhost:5000/api/v1/billboard/info?is_occupied={{is_occupied}} HTTP/1.1

### Register a car without an owner
POST http://localhost:5000/api/v1/ticket-booth/register-car HTTP/1.1
Content-Type: application/json

{
    "license_plate": "ADCXZ879"
}
### Check in a car at a parking space
POST  http://localhost:5000/api/v1/ticket-booth/check-in-car HTTP/1.1
Content-Type: application/json

{
    "license_plate": "ADCXZ879",
    "space_id": "46"
}
### Upadate parking space - occupied
POST  http://localhost:5000/api/v1/ticket-booth/occupy-space HTTP/1.1
Content-Type: application/json

{
    "space_id": "46"
}

### Upadate parking space - free
POST  http://localhost:5000/api/v1/ticket-booth/free-space HTTP/1.1
Content-Type: application/json

{
    "space_id": "46"
}

### Check out a car
POST  http://localhost:5000/api/v1/ticket-booth/check-out-car HTTP/1.1
Content-Type: application/json

{
    "license_plate": "ADCXZ879"
}


### Login in as a test user
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=test@gmail.com
&password=test1234

### Logout
GET http://localhost:5000/auth/logout HTTP/1.1

### Get user invoice for a specified month
@month=5
GET http://localhost:5000/api/v1/users/invoice?month={{month}} HTTP/1.1

### Check sensor alert
GET http://localhost:5000/api/v1/maintenance/sensor-alert HTTP/1.1

### List currently parked cars
@with_owner=1
GET http://localhost:5000/api/v1/maintenance/list-cars?with-owner={{with_owner}} HTTP/1.1

### Overview of amount of cars grouped by
GET http://localhost:5000/api/v1/maintenance/overview-cars?group-by=year HTTP/1.1

### Overview of cars from starting_date until end_date
GET http://localhost:5000/api/v1/finance/list-cars?start-date=2020-05-14%2012:00:00&end-date=2020-06-05%2012:00:00 HTTP/1.1

### Monthly invoice of a car owner
GET  http://localhost:5000/api/v1/finance/invoice/test%40gmail%2Ecom/May HTTP/1.1

### Monthly invoices per car owner
GET  http://localhost:5000/api/v1/finance/invoice/all HTTP/1.1

### Unpaid invoices
GET  http://localhost:5000/api/v1/finance/unpaid HTTP/1.1